### PR TITLE
Allow the project to compile for multiple target frameworks

### PR DESCRIPTION
**Pull request by Bert-Proesmans**
I saw your separate branch for building the project on net core. It seems like you are performing some restructuring as well.
This pull request contains only the required project file changes to build a multitarget nuget package.

I made this change a point release because there shouldn't be any practical user impact between the latest commit and these changes. There is also no guarantee the builds will work perfectly on the other frameworks, but this PR is a start for others to contribute upon.

### CODE REVIEW

**Comment by DavidWDev** [comment]
Hi,

if I see this right, your changes makes the project to a .net core project which does also allow to have it build for .net framework 4.7.2 and 4.8, I'm right?
would that make the .net core nuget package obsolete?

Before I have not mixed the builds for .net framework and .net core. I made the new nuget package just because of another project of mine. I switched to WPF on .net core in general.

As far I remember the WPFMessageBox in the DW.WPFToolkit has some strange problems for .net core.

To be honest, if you look how old the project is meanwhile, beside just build for .net core and 4.8 nothing changed for years. The project is kinda "complete" since 2016 and I wonder that someone is even finding it :D

**Comment by Bert-Proesmans** [comment]
> if I see this right, your changes makes the project to a .net core project which does also allow to have it build for .net framework 4.7.2 and 4.8, I'm right?

Yes, depending on the requirements of the consuming project it will select the build for the most suiting target framework.

> would that make the .net core nuget package obsolete?

I assume you mean the nuget package checked into the repository on your netcore branch. Yes, normally you should be able to build out a single package for all the mentioned target frameworks and push that to nuget.  
I'm currently looking at Github actions to see which commands are required to do this (in my fork)

> Before I have not mixed the builds for .net framework and .net core. I made the new nuget package just because of another project of mine. I switched to WPF on .net core in general.

That might be the best approach honestly, but requires a lot of attention when working on the source. I could see this happening as different projects targetting a single framework with softlinks to the same files.  
That approach does make the packaging step a bit more complicated.

> As far I remember the WPFMessageBox in the DW.WPFToolkit has some strange problems for .net core.

Honestly haven't used it so far.


> To be honest, if you look how old the project is meanwhile, beside just build for .net core and 4.8 nothing changed for years. The project is kinda "complete" since 2016 and I wonder that someone is even finding it :D

It wasn't easy to find, but i required a better ItemsTreeControl and yours works fine so far.

**Comment by Bert-Proesmans** [comment]
I attempted to publish packages with GitHub actions before and it was anything but intuitive and easy. My attempts this evening fell short because of reasons I cannot seem to comprehend. In the end, my GitHub packages account got locked for some reason.  
Frustration is in order in the least. I hope to get this figured out soon so publishing happens automatically.

What do you think about the PR itself? Are you still interested in being in the loop? If not I can fork of course, but it's nicer to have someone to talk about code.

**Comment by DavidWDev** [comment]
For me the DW.WPFToolkit is kinda dead, I from time to time use small parts of it, but thats it.
I have another big (commercial) project on the side, and with that new library packages will come the way, therefore the my-libraries domain is also in work.

I see no problem to merge your PR, but only after I tested on my side how it looks, also the outcome. At the moment I have no really time to do that :-D

Normal work, and after that the side project swallows all I have.

Talk about code, you have something special in mind? We could move it to normal mails david.w.dev at gmail.com

**Comment by Bert-Proesmans** [comment]
Ok, I understand. I'll look into forking the repository then.
I meant to collaborate on this repository when mentioning "talking about code". Nothing specific or serious, only a hobby level.

Thanks for the chat, good luck with future endevours.

**Pull request closed without merging**
